from datetime import date, timedelta

# HAZARD RECORDS  (used by field_agent_screen.py)

# TODO(link: REQ004/REQ011): Replace this hard-coded list with a query to
#   whatever stores hazard records (e.g. a hazards table in your DB, or a
#   results file/endpoint produced by the AI processing pipeline after a
#   drone flight is analyzed). Each real record should still provide:
#     - id unique tree/hazard identifier
#     - severity "high" | "medium" | "low", produced by the AI model
#     - flagged_date date the hazard was detected (for the date filter)
#     - lat, lon real GPS coordinates (for plotting on a real map,
#                        instead of the fake x/y canvas coordinates below)
#     - description short human-readable description of the hazard
#     - status "Pending" | "Reviewed" | "Escalated"
#     - drone_image_path / satellite_image_path -> file paths or URLs to the
#         actual images captured for this tree
#     - ai_summary text generated by the AI reporting module

TODAY = date.today()

HAZARDS = [
    {
        "id": "TC-0142",
        "severity": "high",
        "flagged_date": TODAY - timedelta(days=3),
        # x, y are fake canvas coordinates just for placing a dot on the placeholder map. Replace with real lat/lon once a real map/GIS widget is in place (see field_agent_screen.py map section).
        "x": 90, "y": 75,
        "description": "Leaning 34°, 40m from trail",
        "status": "Pending",
        "drone_image_path": None,       # TODO real file path/URL
        "satellite_image_path": None,   # TODO real file path/URL
        "ai_summary": (
            "Root plate lift detected on the southwest side. Lean angle and "
            "soil disturbance are consistent with an elevated fall risk "
            "within the next storm season."
        ),
    },
    {
        "id": "TC-0198",
        "severity": "high",
        "flagged_date": TODAY - timedelta(days=12),
        "x": 200, "y": 60,
        "description": "Root exposure near creek crossing",
        "status": "Pending",
        "drone_image_path": None,
        "satellite_image_path": None,
        "ai_summary": (
            "Erosion along the creek bank has exposed roughly 40% of the "
            "root structure. Flagged for priority review given proximity "
            "to a foot crossing."
        ),
    },
    {
        "id": "TC-0165",
        "severity": "medium",
        "flagged_date": TODAY - timedelta(days=5),
        "x": 160, "y": 115,
        "description": "Canopy dieback, 15m from campsite",
        "status": "Reviewed",
        "drone_image_path": None,
        "satellite_image_path": None,
        "ai_summary": (
            "Upper canopy shows moderate dieback, likely drought stress. "
            "No immediate structural risk identified."
        ),
    },
    {
        "id": "TC-0071",
        "severity": "low",
        "flagged_date": TODAY - timedelta(days=25),
        "x": 110, "y": 160,
        "description": "Minor lean, monitor next flight",
        "status": "Reviewed",
        "drone_image_path": None,
        "satellite_image_path": None,
        "ai_summary": (
            "Slight lean within normal range for species and site "
            "conditions. No action required at this time."
        ),
    },
    {
        "id": "TC-0203",
        "severity": "medium",
        "flagged_date": TODAY - timedelta(days=40),
        "x": 240, "y": 140,
        "description": "Bark beetle damage observed",
        "status": "Pending",
        "drone_image_path": None,
        "satellite_image_path": None,
        "ai_summary": (
            "Visible beetle galleries on lower trunk. Recommend field "
            "confirmation before next burn season."
        ),
    },
]

# TODO!
#this will need a real check reliant on implementing real data
# Fields:
#   hazard_id (Unique Hazard identifier)
#   agent_a / status_a  first field agent's name and the status they set
#   agent_b / status_b  second field agent's name and the status they set
#   resolved False until an admin picks a final status
CONFLICTS = [
    {
        "hazard_id": "TC-0142",
        "agent_a": "agent 1", "status_a": "Reviewed",
        "agent_b": "agent 2", "status_b": "Escalated",
        "resolved": False,
    }
]


def resolve_conflict(hazard_id: str, final_status: str) -> None:
    hazard = next((h for h in HAZARDS if h["id"] == hazard_id), None)
    if hazard:
        hazard["status"] = final_status

    conflict = next((c for c in CONFLICTS if c["hazard_id"] == hazard_id), None)
    if conflict:
        conflict["resolved"] = True


# WEATHER LOOKUP  (pilot_dashboard.py)
def get_weather_for_coordinates(coords_text: str) -> dict:

    #still no idea how to find extremem weather warning so this is just a placeholder
    """
    `coords_text` is whatever the user typed in the coordinates field, e.g.
    "50.9, -115.1" but will need parse and validation method
    """
    # Mock behavior: deterministic "random" pick based on input length so the UI visibly changes when the coordinates field changes, just so testers can see the field is wired to *something* during demos.
    samples = [
        {"temp_c": 11, "condition": "overcast", "wind_kph": 14},
        {"temp_c": 14, "condition": "light rain", "wind_kph": 22},
        {"temp_c": 18, "condition": "clear", "wind_kph": 31},
        {"temp_c": 9, "condition": "wind advisory", "wind_kph": 8},
    ]
    index = abs(len(coords_text) * 7) % len(samples)
    return samples[index]


def get_extreme_weather_alert() -> str | None:
    
    #still no idea how to find extremem weather warning so this is just a placeholder
    return "Wind gusts over 40 km/h expected after 3:00 PM. Plan flights before then."


# AIRSPACE LOOKUP  (pilot_dashboard.py)
def get_airspace_for_coordinates(coords_text: str) -> dict:
    #still no idea how to find airspace laws so this is just a placeholder
    return {
        "classification": "Class G, uncontrolled below 700 ft",
        "detail": (
            "No active NOTAMs within 5 km. Nearest controlled airspace "
            "boundary is 12 km northeast (Calgary terminal area). Drone "
            "flights permitted up to 122 m (400 ft) AGL without additional "
            "authorization."
        ),
    }


# FLIGHT LOG / SYNC STATUS  (pilot_dashboard.py
# TODO! 
# Replace with real flight records + a real sync timestamp/status 
FLIGHT_LOG = [
    {"date": "2026-07-11", "image_count": 214, "synced": True},
    {"date": "2026-07-04", "image_count": 188, "synced": True},
]

SYNC_STATUS_TEXT = "Last synced 2 minutes ago · all flight logs up to date"




# PDF REPORT GENERATION
# need to update this to the real path for PDF report generation but i don't know how
def generate_pdf_report(hazard_ids: list[str]) -> str:

    return "reports/hazard_report_kananaskis_block_4.pdf"